-- =============================================
-- SEED ADDITIONAL COLLEGES IN THAILAND
-- Run this in Supabase SQL Editor (after seed_colleges.sql)
-- =============================================

-- Insert Additional Thai Colleges
INSERT INTO colleges (name, name_en, is_active) VALUES

-- วิทยาลัยอาชีวศึกษา ครบทุกจังหวัด (Vocational Colleges - By Province)
('วิทยาลัยอาชีวศึกษากระบี่', 'Krabi Vocational College', true),
('วิทยาลัยอาชีวศึกษากาฬสินธุ์', 'Kalasin Vocational College', true),
('วิทยาลัยอาชีวศึกษากำแพงเพชร', 'Kamphaeng Phet Vocational College', true),
('วิทยาลัยอาชีวศึกษาจันทบุรี', 'Chanthaburi Vocational College', true),
('วิทยาลัยอาชีวศึกษาฉะเชิงเทรา', 'Chachoengsao Vocational College', true),
('วิทยาลัยอาชีวศึกษาชลบุรี', 'Chonburi Vocational College', true),
('วิทยาลัยอาชีวศึกษาชัยนาท', 'Chainat Vocational College', true),
('วิทยาลัยอาชีวศึกษาชัยภูมิ', 'Chaiyaphum Vocational College', true),
('วิทยาลัยอาชีวศึกษาชุมพร', 'Chumphon Vocational College', true),
('วิทยาลัยอาชีวศึกษาตรัง', 'Trang Vocational College', true),
('วิทยาลัยอาชีวศึกษาตราด', 'Trat Vocational College', true),
('วิทยาลัยอาชีวศึกษาตาก', 'Tak Vocational College', true),
('วิทยาลัยอาชีวศึกษานครนายก', 'Nakhon Nayok Vocational College', true),
('วิทยาลัยอาชีวศึกษานครปฐม', 'Nakhon Pathom Vocational College', true),
('วิทยาลัยอาชีวศึกษานครพนม', 'Nakhon Phanom Vocational College', true),
('วิทยาลัยอาชีวศึกษานครสวรรค์', 'Nakhon Sawan Vocational College', true),
('วิทยาลัยอาชีวศึกษานครศรีธรรมราช', 'Nakhon Si Thammarat Vocational College', true),
('วิทยาลัยอาชีวศึกษานนทบุรี', 'Nonthaburi Vocational College', true),
('วิทยาลัยอาชีวศึกษานราธิวาส', 'Narathiwat Vocational College', true),
('วิทยาลัยอาชีวศึกษาน่าน', 'Nan Vocational College', true),
('วิทยาลัยอาชีวศึกษาบุรีรัมย์', 'Buriram Vocational College', true),
('วิทยาลัยอาชีวศึกษาปทุมธานี', 'Pathum Thani Vocational College', true),
('วิทยาลัยอาชีวศึกษาประจวบคีรีขันธ์', 'Prachuap Khiri Khan Vocational College', true),
('วิทยาลัยอาชีวศึกษาปราจีนบุรี', 'Prachin Buri Vocational College', true),
('วิทยาลัยอาชีวศึกษาปัตตานี', 'Pattani Vocational College', true),
('วิทยาลัยอาชีวศึกษาพระนครศรีอยุธยา', 'Ayutthaya Vocational College', true),
('วิทยาลัยอาชีวศึกษาพะเยา', 'Phayao Vocational College', true),
('วิทยาลัยอาชีวศึกษาพังงา', 'Phang Nga Vocational College', true),
('วิทยาลัยอาชีวศึกษาพัทลุง', 'Phatthalung Vocational College', true),
('วิทยาลัยอาชีวศึกษาเพชรบุรี', 'Phetchaburi Vocational College', true),
('วิทยาลัยอาชีวศึกษาเพชรบูรณ์', 'Phetchabun Vocational College', true),
('วิทยาลัยอาชีวศึกษาแพร่', 'Phrae Vocational College', true),
('วิทยาลัยอาชีวศึกษามหาสารคาม', 'Maha Sarakham Vocational College', true),
('วิทยาลัยอาชีวศึกษามุกดาหาร', 'Mukdahan Vocational College', true),
('วิทยาลัยอาชีวศึกษาแม่ฮ่องสอน', 'Mae Hong Son Vocational College', true),
('วิทยาลัยอาชีวศึกษายะลา', 'Yala Vocational College', true),
('วิทยาลัยอาชีวศึกษายโสธร', 'Yasothon Vocational College', true),
('วิทยาลัยอาชีวศึกษาร้อยเอ็ด', 'Roi Et Vocational College', true),
('วิทยาลัยอาชีวศึกษาระนอง', 'Ranong Vocational College', true),
('วิทยาลัยอาชีวศึกษาระยอง', 'Rayong Vocational College', true),
('วิทยาลัยอาชีวศึกษาราชบุรี', 'Ratchaburi Vocational College', true),
('วิทยาลัยอาชีวศึกษาลพบุรี', 'Lopburi Vocational College', true),
('วิทยาลัยอาชีวศึกษาลำปาง', 'Lampang Vocational College', true),
('วิทยาลัยอาชีวศึกษาลำพูน', 'Lamphun Vocational College', true),
('วิทยาลัยอาชีวศึกษาเลย', 'Loei Vocational College', true),
('วิทยาลัยอาชีวศึกษาศรีสะเกษ', 'Si Sa Ket Vocational College', true),
('วิทยาลัยอาชีวศึกษาสกลนคร', 'Sakon Nakhon Vocational College', true),
('วิทยาลัยอาชีวศึกษาสงขลา', 'Songkhla Vocational College', true),
('วิทยาลัยอาชีวศึกษาสตูล', 'Satun Vocational College', true),
('วิทยาลัยอาชีวศึกษาสมุทรปราการ', 'Samut Prakan Vocational College', true),
('วิทยาลัยอาชีวศึกษาสมุทรสงคราม', 'Samut Songkhram Vocational College', true),
('วิทยาลัยอาชีวศึกษาสมุทรสาคร', 'Samut Sakhon Vocational College', true),
('วิทยาลัยอาชีวศึกษาสระแก้ว', 'Sa Kaeo Vocational College', true),
('วิทยาลัยอาชีวศึกษาสระบุรี', 'Saraburi Vocational College', true),
('วิทยาลัยอาชีวศึกษาสิงห์บุรี', 'Sing Buri Vocational College', true),
('วิทยาลัยอาชีวศึกษาสุโขทัย', 'Sukhothai Vocational College', true),
('วิทยาลัยอาชีวศึกษาสุพรรณบุรี', 'Suphan Buri Vocational College', true),
('วิทยาลัยอาชีวศึกษาสุรินทร์', 'Surin Vocational College', true),
('วิทยาลัยอาชีวศึกษาเสาวภา', 'Saowapa Vocational College', true),
('วิทยาลัยอาชีวศึกษาหนองคาย', 'Nong Khai Vocational College', true),
('วิทยาลัยอาชีวศึกษาหนองบัวลำภู', 'Nong Bua Lamphu Vocational College', true),
('วิทยาลัยอาชีวศึกษาอ่างทอง', 'Ang Thong Vocational College', true),
('วิทยาลัยอาชีวศึกษาอำนาจเจริญ', 'Amnat Charoen Vocational College', true),
('วิทยาลัยอาชีวศึกษาอุตรดิตถ์', 'Uttaradit Vocational College', true),
('วิทยาลัยอาชีวศึกษาอุทัยธานี', 'Uthai Thani Vocational College', true),
('วิทยาลัยอาชีวศึกษาอุบลราชธานี', 'Ubon Ratchathani Vocational College', true),
('วิทยาลัยอาชีวศึกษาเอี่ยมละออ', 'Iam La-or Vocational College', true),

-- วิทยาลัยเทคโนโลยีเอกชนชื่อดัง (Private Technology Colleges)
('วิทยาลัยเทคโนโลยีภาคตะวันออก (อี.เทค)', 'Eastern Technological College (E.TECH)', true),
('วิทยาลัยเทคโนโลยีชลพินิจ', 'Cholpinij Technology College', true),
('วิทยาลัยเทคโนโลยีศรีสะเกษบริหารธุรกิจ', 'Si Sa Ket Business Administration Technology College', true),
('วิทยาลัยเทคโนโลยีอีสานเหนือ', 'North-Eastern Technology College', true),
('วิทยาลัยเทคโนโลยีพณิชยการอยุธยา', 'Ayutthaya Commercial Technology College', true),
('วิทยาลัยเทคโนโลยีหมู่บ้านครู', 'Mubankhru Technology College', true),
('วิทยาลัยเทคโนโลยีวิมลบริหารธุรกิจ', 'Wimol Business Administration Technology College', true),
('วิทยาลัยเทคโนโลยีไทยอโยธยาบริหารธุรกิจ', 'Thai Ayothaya Business Technology College', true),
('วิทยาลัยเทคโนโลยีไออาร์พีซี', 'IRPC Technology College', true),
('วิทยาลัยเทคโนโลยีปัญญาภิวัฒน์', 'Panyapiwat Technology College', true),
('วิทยาลัยเทคโนโลยีซีพีออลล์', 'CP All Technology College', true),
('วิทยาลัยเทคโนโลยีบริหารธุรกิจกรุงเทพ', 'Bangkok Business Technology College', true),

-- วิทยาลัยพาณิชยการ เพิ่มเติม (Commercial Colleges)
('วิทยาลัยพาณิชยการอินทราชัย', 'Intrarachai Commercial College', true),
('วิทยาลัยพณิชยการปราจีนบุรี', 'Prachin Buri Commercial College', true),
('วิทยาลัยพาณิชยการจันทบุรี', 'Chanthaburi Commercial College', true),
('วิทยาลัยพาณิชยการบางพลี', 'Bang Phli Commercial College', true),
('วิทยาลัยพาณิชยการราชดำเนิน', 'Rajdamnern Commercial College', true),

-- วิทยาลัยการอาชีพ ยอดนิยม (Vocational Training Colleges)
('วิทยาลัยการอาชีพศรีสำโรง', 'Si Samrong Vocational Training College', true),
('วิทยาลัยการอาชีพกาญจนบุรี', 'Kanchanaburi Vocational Training College', true),
('วิทยาลัยการอาชีพบางปะกง', 'Bang Pakong Vocational Training College', true),
('วิทยาลัยการอาชีพพนัสนิคม', 'Phanat Nikhom Vocational Training College', true),
('วิทยาลัยการอาชีพบ้านโพธิ์', 'Ban Pho Vocational Training College', true),
('วิทยาลัยการอาชีพกระนวน', 'Kranuan Vocational Training College', true),
('วิทยาลัยการอาชีพบ้านไผ่', 'Ban Phai Vocational Training College', true),
('วิทยาลัยการอาชีพชุมแพ', 'Chum Phae Vocational Training College', true),
('วิทยาลัยการอาชีพสว่างแดนดิน', 'Sawang Daen Din Vocational Training College', true),
('วิทยาลัยการอาชีพวังไกลกังวล', 'Wang Klai Kangwon Vocational Training College', true),
('วิทยาลัยการอาชีพปราณบุรี', 'Pran Buri Vocational Training College', true),

-- วิทยาลัยสารพัดช่าง (Polytechnic Colleges)
('วิทยาลัยสารพัดช่างกรุงเทพ', 'Bangkok Polytechnic College', true),
('วิทยาลัยสารพัดช่างนครหลวง', 'Nakhon Luang Polytechnic College', true),
('วิทยาลัยสารพัดช่างพระนคร', 'Phra Nakhon Polytechnic College', true),
('วิทยาลัยสารพัดช่างธนบุรี', 'Thonburi Polytechnic College', true),
('วิทยาลัยสารพัดช่างสี่พระยา', 'Si Phraya Polytechnic College', true),
('วิทยาลัยสารพัดช่างสมุทรปราการ', 'Samut Prakan Polytechnic College', true),
('วิทยาลัยสารพัดช่างนนทบุรี', 'Nonthaburi Polytechnic College', true),
('วิทยาลัยสารพัดช่างปทุมธานี', 'Pathum Thani Polytechnic College', true),
('วิทยาลัยสารพัดช่างเชียงใหม่', 'Chiang Mai Polytechnic College', true),
('วิทยาลัยสารพัดช่างขอนแก่น', 'Khon Kaen Polytechnic College', true),

-- วิทยาลัยเกษตรและเทคโนโลยี (Agricultural Colleges)
('วิทยาลัยเกษตรและเทคโนโลยีเชียงใหม่', 'Chiang Mai Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีเพชรบุรี', 'Phetchaburi Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีชลบุรี', 'Chonburi Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีนครสวรรค์', 'Nakhon Sawan Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีสุพรรณบุรี', 'Suphan Buri Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีอุดรธานี', 'Udon Thani Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีสงขลา', 'Songkhla Agricultural Technology College', true),
('วิทยาลัยเกษตรและเทคโนโลยีกระบี่', 'Krabi Agricultural Technology College', true)

ON CONFLICT (name) DO NOTHING;

-- Show updated count
SELECT COUNT(*) as total_colleges FROM colleges;
